version: "3"

networks:
  app-tier:
    driver: bridge

volumes:
  vol1:
  vol2:
  zk_data:
  kafka_data:

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zk_data:/bitnami
    networks:
      - app-tier
