version: "3"

networks:
  app-tier:
    driver: bridge

volumes:
  vol1:
  vol2:
  zk_data:
  kafka_data:

services:
  minio:
    image: 'minio/minio'
    command: 'server /data'
    ports:
      - '9000:9000'
    networks:
      - app-tier
    volumes:
      - vol1:/data
    environment:
      - MINIO_ACCESS_KEY=key
      - MINIO_SECRET_KEY=aryaman02

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - app-tier
    volumes:
      - vol2:/data/db

  redis:
#    container_name: 'td-redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - app-tier

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zk_data:/bitnami
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    networks:
      - app-tier
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

#  aggregator-svc:
#    image: 'aggregator-svc:latest'
#    scale: 1
#    networks:
#      - app-tier
#    environment:
#      - KAFKA_HOST=kafka
#      - REDIS_HOST=redis
#      - MONGO_HOST=mongo
#    depends_on:
#      - kafka
#      - redis
#      - mongo

#  processor-svc:
#    image: 'processor-svc:latest'
#    scale: 1
#    networks:
#      - app-tier
#    environment:
#      - KAFKA_HOST=kafka
#      - MONGO_HOST=mongo
#    depends_on:
#      - kafka
#      - mongo

  grpc-svc:
    image: 'grpc-svc:latest'
    scale: 1
    networks:
      - app-tier
    ports:
      - '8746:8746'
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo

  rest-svc:
    image: 'rest-svc:latest'
    scale: 1
    networks:
      - app-tier
    ports:
      - '8080:8080'
    environment:
      - KAFKA_HOST=kafka
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - MINIO_HOST=minio
      - GRPC_HOST=grpc-svc
    depends_on:
      - kafka
      - redis
      - mongo
      - minio
      - grpc-svc
