FROM openjdk:11

RUN apt-get update && apt-get install net-tools

ADD BMovieProj-0.0.1-SNAPSHOT.jar /tmp

ENV KAFKA_HOST 0.0.0.0
ENV REDIS_HOST 0.0.0.0
ENV MINIO_HOST 0.0.0.0

WORKDIR /tmp
ENTRYPOINT java -jar BMovieProj-0.0.1-SNAPSHOT.jar com.example.demo.DemoApplication
